/* tslint:disable */
/* eslint-disable */
/**
 * Biblio API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Factum,
  FondsDocumentaire,
  FondsJohannique,
  Imprime,
  IndexPaysLorrain,
  Manuscrit,
} from '../models/index';
import {
    FactumFromJSON,
    FactumToJSON,
    FondsDocumentaireFromJSON,
    FondsDocumentaireToJSON,
    FondsJohanniqueFromJSON,
    FondsJohanniqueToJSON,
    ImprimeFromJSON,
    ImprimeToJSON,
    IndexPaysLorrainFromJSON,
    IndexPaysLorrainToJSON,
    ManuscritFromJSON,
    ManuscritToJSON,
} from '../models/index';

/**
 * SearchApi - interface
 * 
 * @export
 * @interface SearchApiInterface
 */
export interface SearchApiInterface {
    /**
     * 
     * @summary Search for factums
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchFactumsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Factum>>>;

    /**
     * Search for factums
     */
    searchFactumsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Factum>>;

    /**
     * 
     * @summary Search for fonds documentaire
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchFondsDocumentaireGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FondsDocumentaire>>>;

    /**
     * Search for fonds documentaire
     */
    searchFondsDocumentaireGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FondsDocumentaire>>;

    /**
     * 
     * @summary Search for fonds johannique
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchFondsJohanniqueGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FondsJohannique>>>;

    /**
     * Search for fonds johannique
     */
    searchFondsJohanniqueGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FondsJohannique>>;

    /**
     * 
     * @summary Search for imprimes
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchImprimesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Imprime>>>;

    /**
     * Search for imprimes
     */
    searchImprimesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Imprime>>;

    /**
     * 
     * @summary Search for index pays lorrain
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchIndexPaysLorrainGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IndexPaysLorrain>>>;

    /**
     * Search for index pays lorrain
     */
    searchIndexPaysLorrainGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IndexPaysLorrain>>;

    /**
     * 
     * @summary Search for manuscrits
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApiInterface
     */
    searchManuscritsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manuscrit>>>;

    /**
     * Search for manuscrits
     */
    searchManuscritsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manuscrit>>;

}

/**
 * 
 */
export class SearchApi extends runtime.BaseAPI implements SearchApiInterface {

    /**
     * Search for factums
     */
    async searchFactumsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Factum>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/searchFactums`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FactumFromJSON));
    }

    /**
     * Search for factums
     */
    async searchFactumsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Factum>> {
        const response = await this.searchFactumsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search for fonds documentaire
     */
    async searchFondsDocumentaireGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FondsDocumentaire>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/searchFondsDocumentaire`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FondsDocumentaireFromJSON));
    }

    /**
     * Search for fonds documentaire
     */
    async searchFondsDocumentaireGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FondsDocumentaire>> {
        const response = await this.searchFondsDocumentaireGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search for fonds johannique
     */
    async searchFondsJohanniqueGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<FondsJohannique>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/searchFondsJohannique`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FondsJohanniqueFromJSON));
    }

    /**
     * Search for fonds johannique
     */
    async searchFondsJohanniqueGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<FondsJohannique>> {
        const response = await this.searchFondsJohanniqueGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search for imprimes
     */
    async searchImprimesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Imprime>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/searchImprimes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ImprimeFromJSON));
    }

    /**
     * Search for imprimes
     */
    async searchImprimesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Imprime>> {
        const response = await this.searchImprimesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search for index pays lorrain
     */
    async searchIndexPaysLorrainGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<IndexPaysLorrain>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/searchIndexPaysLorrain`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(IndexPaysLorrainFromJSON));
    }

    /**
     * Search for index pays lorrain
     */
    async searchIndexPaysLorrainGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<IndexPaysLorrain>> {
        const response = await this.searchIndexPaysLorrainGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search for manuscrits
     */
    async searchManuscritsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Manuscrit>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/searchManuscrits`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ManuscritFromJSON));
    }

    /**
     * Search for manuscrits
     */
    async searchManuscritsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Manuscrit>> {
        const response = await this.searchManuscritsGetRaw(initOverrides);
        return await response.value();
    }

}
