/* tslint:disable */
/* eslint-disable */
/**
 * Biblio API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManuscritMetadatas
 */
export interface ManuscritMetadatas {
    /**
     * 
     * @type {string}
     * @memberof ManuscritMetadatas
     */
    commentaires?: string;
}

/**
 * Check if a given object implements the ManuscritMetadatas interface.
 */
export function instanceOfManuscritMetadatas(value: object): value is ManuscritMetadatas {
    return true;
}

export function ManuscritMetadatasFromJSON(json: any): ManuscritMetadatas {
    return ManuscritMetadatasFromJSONTyped(json, false);
}

export function ManuscritMetadatasFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManuscritMetadatas {
    if (json == null) {
        return json;
    }
    return {
        
        'commentaires': json['commentaires'] == null ? undefined : json['commentaires'],
    };
}

  export function ManuscritMetadatasToJSON(json: any): ManuscritMetadatas {
      return ManuscritMetadatasToJSONTyped(json, false);
  }

  export function ManuscritMetadatasToJSONTyped(value?: ManuscritMetadatas | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commentaires': value['commentaires'],
    };
}

