image: node:16.13.2-alpine

stages:
  - build

# cache:
#   key: ${CI_COMMIT_SHA}
#   paths:
#     - node_modules/

build:
  stage: build
  script:
    - yarn install
  # artifacts:
  #   paths:
  #     - build/