stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/


install:
  stage: install
  script:
    # Run ESLint
    - yarn install

test:
  stage: test
  script:
    # Run ESLint
    - yarn run lint



build:
  stage: build
  script:
    - yarn run tsc 
    - yarn run vite build
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days
    paths:
      - dist/



deploy:
  stage: deploy
  script:
    # Deploy to remote server
    - rsync -rvog --delete --chmod=774 --chown=$DEPLOY_USER:$DEPLOY_GROUP  dist/ $DEPLOY_USER@$SERVER_IP:$DEPLOY_PATH