/* tslint:disable */
/* eslint-disable */
/**
 * Biblio API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FondsDocumentaireMetadatas } from './FondsDocumentaireMetadatas';
import {
    FondsDocumentaireMetadatasFromJSON,
    FondsDocumentaireMetadatasFromJSONTyped,
    FondsDocumentaireMetadatasToJSON,
    FondsDocumentaireMetadatasToJSONTyped,
} from './FondsDocumentaireMetadatas';

/**
 * 
 * @export
 * @interface FondsDocumentaire
 */
export interface FondsDocumentaire {
    /**
     * 
     * @type {FondsDocumentaireMetadatas}
     * @memberof FondsDocumentaire
     */
    metadatas?: FondsDocumentaireMetadatas;
    /**
     * 
     * @type {Array<string>}
     * @memberof FondsDocumentaire
     */
    urls?: Array<string>;
}

/**
 * Check if a given object implements the FondsDocumentaire interface.
 */
export function instanceOfFondsDocumentaire(value: object): value is FondsDocumentaire {
    return true;
}

export function FondsDocumentaireFromJSON(json: any): FondsDocumentaire {
    return FondsDocumentaireFromJSONTyped(json, false);
}

export function FondsDocumentaireFromJSONTyped(json: any, ignoreDiscriminator: boolean): FondsDocumentaire {
    if (json == null) {
        return json;
    }
    return {
        
        'metadatas': json['metadatas'] == null ? undefined : FondsDocumentaireMetadatasFromJSON(json['metadatas']),
        'urls': json['urls'] == null ? undefined : json['urls'],
    };
}

  export function FondsDocumentaireToJSON(json: any): FondsDocumentaire {
      return FondsDocumentaireToJSONTyped(json, false);
  }

  export function FondsDocumentaireToJSONTyped(value?: FondsDocumentaire | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadatas': FondsDocumentaireMetadatasToJSON(value['metadatas']),
        'urls': value['urls'],
    };
}

