/* tslint:disable */
/* eslint-disable */
/**
 * Biblio API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImprimeMetadatas } from './ImprimeMetadatas';
import {
    ImprimeMetadatasFromJSON,
    ImprimeMetadatasFromJSONTyped,
    ImprimeMetadatasToJSON,
    ImprimeMetadatasToJSONTyped,
} from './ImprimeMetadatas';

/**
 * 
 * @export
 * @interface Imprime
 */
export interface Imprime {
    /**
     * 
     * @type {ImprimeMetadatas}
     * @memberof Imprime
     */
    metadatas?: ImprimeMetadatas;
    /**
     * 
     * @type {Array<string>}
     * @memberof Imprime
     */
    urls?: Array<string>;
}

/**
 * Check if a given object implements the Imprime interface.
 */
export function instanceOfImprime(value: object): value is Imprime {
    return true;
}

export function ImprimeFromJSON(json: any): Imprime {
    return ImprimeFromJSONTyped(json, false);
}

export function ImprimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Imprime {
    if (json == null) {
        return json;
    }
    return {
        
        'metadatas': json['metadatas'] == null ? undefined : ImprimeMetadatasFromJSON(json['metadatas']),
        'urls': json['urls'] == null ? undefined : json['urls'],
    };
}

  export function ImprimeToJSON(json: any): Imprime {
      return ImprimeToJSONTyped(json, false);
  }

  export function ImprimeToJSONTyped(value?: Imprime | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadatas': ImprimeMetadatasToJSON(value['metadatas']),
        'urls': value['urls'],
    };
}

