/* tslint:disable */
/* eslint-disable */
/**
 * Biblio API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ManuscritMetadatas } from './ManuscritMetadatas';
import {
    ManuscritMetadatasFromJSON,
    ManuscritMetadatasFromJSONTyped,
    ManuscritMetadatasToJSON,
    ManuscritMetadatasToJSONTyped,
} from './ManuscritMetadatas';

/**
 * 
 * @export
 * @interface IndexPaysLorrain
 */
export interface IndexPaysLorrain {
    /**
     * 
     * @type {ManuscritMetadatas}
     * @memberof IndexPaysLorrain
     */
    metadatas?: ManuscritMetadatas;
}

/**
 * Check if a given object implements the IndexPaysLorrain interface.
 */
export function instanceOfIndexPaysLorrain(value: object): value is IndexPaysLorrain {
    return true;
}

export function IndexPaysLorrainFromJSON(json: any): IndexPaysLorrain {
    return IndexPaysLorrainFromJSONTyped(json, false);
}

export function IndexPaysLorrainFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndexPaysLorrain {
    if (json == null) {
        return json;
    }
    return {
        
        'metadatas': json['metadatas'] == null ? undefined : ManuscritMetadatasFromJSON(json['metadatas']),
    };
}

  export function IndexPaysLorrainToJSON(json: any): IndexPaysLorrain {
      return IndexPaysLorrainToJSONTyped(json, false);
  }

  export function IndexPaysLorrainToJSONTyped(value?: IndexPaysLorrain | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadatas': ManuscritMetadatasToJSON(value['metadatas']),
    };
}

