const mockedSearchResult = {
  kind: 'BIBLIOTHEQUE_PAGE_IMPRIMES',
  result: [
    {
      numero: 'numero_mock_1',
      fonds: 'fond_mock_1',
      type_document: 'type_doc_mock_1',
      auteur: 'auteur_mock_1',
      auteur_bis: 'auteur_bis_mock_1',
      titre: 'titre_mock_1',
      couverture: 'couverture_mock_1',
      langue: 'langue_mock_1',
      edition: 'edition_mock_1',
      datation: 'datation_mock_1',
      contenu: 'contenu_mock_1',
      etat: 'etat_mock_1',
      ancien_proprio: 'ancien_proprio_mock_1',
      note: 'note_mock_1',
      don: 'don_mock_1',
      emplacement_initial: 'emplacement_initial_mock_1',
      epi: 'epi_mock_1',
      travee: 'travee_mock_1',
      tablette: 'tablette_mock_1',
      format: 'format_mock_1',
      annee: 'annee_mock_1',
      cote: 'cote_mock_1',
      tome: 'tome_mock_1',
      metrage_ou_commentaire: 'metrag_mock_1',
      carton: 'carton_mock_1',
      urls: ['url1_mock_1', 'url2_mock_1'],
    },
    {
      numero: 'numero_mock_2',
      fonds: 'fond_mock_2',
      type_document: 'type_doc_mock_2',
      auteur: 'auteur_mock_2',
      auteur_bis: 'auteur_bis_mock_2',
      titre: 'titre_mock_2',
      couverture: 'couverture_mock_2',
      langue: 'langue_mock_2',
      edition: 'edition_mock_2',
      datation: 'datation_mock_2',
      contenu: 'contenu_mock_2',
      etat: 'etat_mock_2',
      ancien_proprio: 'ancien_proprio_mock_2',
      note: 'note_mock_2',
      don: 'don_mock_2',
      emplacement_initial: 'emplacement_initial_mock_2',
      epi: 'epi_mock_2',
      travee: 'travee_mock_2',
      tablette: 'tablette_mock_2',
      format: 'format_mock_2',
      annee: 'annee_mock_2',
      cote: 'cote_mock_2',
      tome: 'tome_mock_2',
      metrage_ou_commentaire: 'metrag_mock_2',
      carton: 'carton_mock_2',
      urls: ['url1_mock_2', 'url2_mock_2'],
    },
  ],
};

export default mockedSearchResult;
