openapi: 3.1.0
info:
  title: Biblio API
  version: 1.0.0
paths:
  /search/imprimes:
    get:
      summary: Search for imprimes
      tags:
        - search
      parameters:
        - name: author
          in: query
          description: author search parameter
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: title search parameter
          required: false
          schema:
            type: string
        - name: keywords
          in: query
          description: keywords search parameter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of imprimes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Imprime'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /search/factums:
    get:
      summary: Search for factums
      tags:
        - search
      parameters:
        - name: author
          in: query
          description: author search parameter
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: title search parameter
          required: false
          schema:
            type: string
        - name: keywords
          in: query
          description: keywords search parameter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of factums
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Factum'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /search/fondsJohannique:
    get:
      summary: Search for fonds johannique
      tags:
        - search
      parameters:
        - name: author
          in: query
          description: author search parameter
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: title search parameter
          required: false
          schema:
            type: string
        - name: keywords
          in: query
          description: keywords search parameter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of fonds johannique
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FondsJohannique'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /search/fonds_documentaire:
    get:
      summary: Search for fonds documentaire
      tags:
        - search
      parameters:
        - name: author
          in: query
          description: author search parameter
          required: false
          schema:
            type: string
        - name: title
          in: query
          description: title search parameter
          required: false
          schema:
            type: string
        - name: keywords
          in: query
          description: keywords search parameter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of fonds documentaire
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FondsDocumentaire'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /search/manuscrits:
    get:
      summary: Search for manuscrits
      tags:
        - search
      parameters:
        - name: keywords
          in: query
          description: keywords search parameter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of manuscrits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Manuscrit'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /search/index_pays_lorrain:
    get:
      summary: Search for index pays lorrain
      tags:
        - search
      parameters:
        - name: keywords
          in: query
          description: keywords search parameter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of index pays lorrain
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IndexPaysLorrain'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /stats/imprimes:
    get:
      summary: Stats on the imprimes
      tags:
        - stats
      responses:
        '200':
          description: Stats on the imprimes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /stats/factums:
    get:
      summary: Stats on the factums
      tags:
        - stats
      responses:
        '200':
          description: Stats on the factums
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /stats/fonds_documentaire:
    get:
      summary: Stats on the fonds documentaire
      tags:
        - stats
      responses:
        '200':
          description: Stats on the fonds documentaire
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /stats/fonds_johannique:
    get:
      summary: Stats on the fonds johannique
      tags:
        - stats
      responses:
        '200':
          description: Stats on the fonds johannique
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /stats/manuscrits:
    get:
      summary: Stats on the manuscrits
      tags:
        - stats
      responses:
        '200':
          description: Stats on the manuscrits
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
        '404':
          description: Not found
        '500':
          description: Internal server error
  /stats/index_pays_lorrain:
    get:
      summary: Stats on the index pays lorrain
      tags:
        - stats
      responses:
        '200':
          description: Stats on the index pays lorrain
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stats'
        '404':
          description: Not found
        '500':
          description: Internal server error
components:
  schemas:
    Imprime:
      type: object
      properties:
        metadatas:
          type: object
          properties:
              epi:
                type: string
              travee:
                type: string
              tablette:
                type: string
              cote:
                type: string
              ordre:
                type: string
              lieu:
                type: string
              format:
                type: string
              auteur:
                type: string
              titre:
                type: string
              annee:
                type: string
              tome:
                type: string
              etat:
                type: string
              commentaire:
                type: string
        urls:
          type: array
          items:
              type: string
    Factum:
        type: object
        properties:
          metadatas:
            type: object
            properties:
                cote:
                  type: string
                tome:
                  type: string
                type:
                  type: string
                auteur:
                  type: string
                titre:
                  type: string
                couverture:
                  type: string
                langue:
                  type: string
                edition:
                  type: string
                datation:
                  type: string
                contenu:
                  type: string
                etat:
                  type: string
                notes:
                  type: string
                emplacement:
                  type: string
          urls:
            type: array
            items:
                type: string
    FondsJohannique:
        type: object
        properties:
          metadatas:
            type: object
            properties:
                epi:
                  type: string
                travee:
                  type: string
                tablette:
                  type: string
                cote:
                  type: string
                ordre:
                  type: string
                lieu:
                  type: string
                format:
                  type: string
                auteur:
                  type: string
                titre:
                  type: string
                annee:
                  type: string
                tome:
                  type: string
                etat:
                  type: string
                commentaire:
                  type: string
          urls:
            type: array
            items:
                type: string
    FondsDocumentaire:
        type: object
        properties:
          metadatas:
            type: object
            properties:
                n_carton:
                  type: string
                fonds:
                  type: string
                type_de_document:
                  type: string
                auteur:
                  type: string
                auteur_bis:
                  type: string
                titre:
                  type: string
                couverture:
                  type: string
                langue:
                  type: string
                edition:
                  type: string
                datation:
                  type: string
                contenu:
                  type: string
                etat:
                  type: string
                ancien_proprietaire:
                  type: string
                notes:
                  type: string
                don:
                  type: string
                emplacement_initial_dans_la_bibliotheque:
                  type: string
          urls:
            type: array
            items:
                type: string
    Manuscrit:
        type: object
        properties:
          metadatas:
            type: object
            properties:
                commentaires:
                  type: string
    IndexPaysLorrain:
        type: object
        properties:
          metadatas:
            type: object
            properties:
                commentaires:
                  type: string
    Stats:
        type: object
        properties:
          count:
            type: integer
